###
# configures the server and installs the web application
##
- include: ubuntu.yml

- include: nginx_ssl.yml
  when: deploy_ssl

- include: nginx_no_ssl.yml
  when: not deploy_ssl

- include: git.yml
- include: postgresql.yml
- include: redis.yml
- include: dependencies.yml
- include: wsgi.yml

- include: celery.yml

- name: alert that deployment is complete
  twilio:
    msg: "Deployment complete!"
    account_sid: "{{ wsgi_env_vars.TWILIO_ACCOUNT_SID }}"
    auth_token: "{{ wsgi_env_vars.TWILIO_AUTH_TOKEN }}"
    from_number: "{{ wsgi_env_vars.TWILIO_NUMBER }}"
    to_number: "{{ alert_number }}"
  delegate_to: localhost
  when: deployment_alert
